<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-HBharish-1" ignored="0" name="Login Test" tests="1" failures="1" timestamp="24 Apr 2017 12:19:24 GMT" time="4.438" errors="0">
  <testcase name="doLogin" time="4.097" classname="com.unisys.pom.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.unisys.pom.testcases.base.BaseTest.init(BaseTest.java:86)
	at com.unisys.pom.testcases.LoginTest.doLogin(LoginTest.java:32)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Login Test -->
